use_frameworks!

platform :ios, 9.0

target 'CoinpaprikaAPI_Example' do
  pod 'CoinpaprikaAPI', :path => '../'

  target 'CoinpaprikaAPI_Tests' do
    inherit! :search_paths

    
  end
end

target 'CoinpaprikaAPI_Example_tvOS' do
    pod 'CoinpaprikaAPI', :path => '../'
    
    target 'CoinpaprikaAPI_Example_tvOSTests' do
        inherit! :search_paths
        
        
    end
end

target 'CoinpaprikaAPI_Example_macOS' do
    pod 'CoinpaprikaAPI', :path => '../'
    
    target 'CoinpaprikaAPI_Example_macOSTests' do
        inherit! :search_paths
        
        
    end
end
