use_frameworks!

target 'CoinpaprikaAPI_Example' do
  platform :ios, 10.0
  
  pod 'CoinpaprikaAPI', :path => '../'

  target 'CoinpaprikaAPI_Tests' do
    inherit! :search_paths

    
  end
end

target 'CoinpaprikaAPI_Example_tvOS' do
    platform :tvos, 12.0
    
    pod 'CoinpaprikaAPI', :path => '../'
    
    target 'CoinpaprikaAPI_Example_tvOSTests' do
        inherit! :search_paths
        
        
    end
end

target 'CoinpaprikaAPI_Example_macOS' do
    platform :osx, 10.14
    
    pod 'CoinpaprikaAPI', :path => '../'
    
    target 'CoinpaprikaAPI_Example_macOSTests' do
        inherit! :search_paths
        
        
    end
end
