#if !canImport(ObjectiveC)
import XCTest

extension CodableTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableTest = [
        ("testTickerEncodeDecode", testTickerEncodeDecode),
    ]
}

extension ErrorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorsTests = [
        ("testRequestLocalizedErrors", testRequestLocalizedErrors),
        ("testResponseErrorUrl", testResponseErrorUrl),
        ("testResponseLocalizedErrors", testResponseLocalizedErrors),
    ]
}

extension QuotesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuotesTests = [
        ("testQuoteSymbols", testQuoteSymbols),
    ]
}

extension RequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RequestTests = [
        ("testCoinDetailsRequest", testCoinDetailsRequest),
        ("testCoinExchangesRequest", testCoinExchangesRequest),
        ("testCoinHistoricalOhlcvRequest", testCoinHistoricalOhlcvRequest),
        ("testCoinLatestOhlcvRequest", testCoinLatestOhlcvRequest),
        ("testCoinMarketsRequest", testCoinMarketsRequest),
        ("testCoinsRequest", testCoinsRequest),
        ("testEventsRequest", testEventsRequest),
        ("testExchangeRequest", testExchangeRequest),
        ("testFailureResponse", testFailureResponse),
        ("testFiatsRequest", testFiatsRequest),
        ("testGlobalStatsRequest", testGlobalStatsRequest),
        ("testMarketRequest", testMarketRequest),
        ("testPersonRequest", testPersonRequest),
        ("testRequestError", testRequestError),
        ("testSearchRequest", testSearchRequest),
        ("testSearchWithoutCoins", testSearchWithoutCoins),
        ("testSuccessResponse", testSuccessResponse),
        ("testTickerHistoryRequest", testTickerHistoryRequest),
        ("testTickerRequest", testTickerRequest),
        ("testTickersRequest", testTickersRequest),
        ("testTweetRequest", testTweetRequest),
        ("testTweetsRequest", testTweetsRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodableTest.__allTests__CodableTest),
        testCase(ErrorsTests.__allTests__ErrorsTests),
        testCase(QuotesTests.__allTests__QuotesTests),
        testCase(RequestTests.__allTests__RequestTests),
    ]
}
#endif
